### ISSUE TITLE
StringIndexOutOfBoundsException exception if model POJO has a get() method

### ISSUE THREAD

**Issue by fdlk** [bpatters/schemagen-graphql#10]
One of my model POJO's has a get() method.
When I create the schema, I get the following StringIndexOutOfBoundsException:

```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 4
	at java.lang.String.substring(String.java:1963) ~[na:1.8.0_112]
	at com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper.getFieldNameFromMethod(GraphQLObjectMapper.java:162) ~[schemagen-graphql-1.0.1.jar:na]
	at com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper.getGraphQLFieldDefinitions(GraphQLObjectMapper.java:664) ~[schemagen-graphql-1.0.1.jar:na]
	at com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper.buildObject(GraphQLObjectMapper.java:610) ~[schemagen-graphql-1.0.1.jar:na]
	at com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper.getOutputType(GraphQLObjectMapper.java:496) ~[schemagen-graphql-1.0.1.jar:na]
	at com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper.getFieldType(GraphQLObjectMapper.java:245) ~[schemagen-graphql-1.0.1.jar:na]
	at com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper.getGraphQLFieldDefinitions(GraphQLObjectMapper.java:673) ~[schemagen-graphql-1.0.1.jar:na]
	at com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper.buildObject(GraphQLObjectMapper.java:610) ~[schemagen-graphql-1.0.1.jar:na]
	at com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper.getOutputType(GraphQLObjectMapper.java:496) ~[schemagen-graphql-1.0.1.jar:na]
	at com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper.getFieldType(GraphQLObjectMapper.java:245) ~[schemagen-graphql-1.0.1.jar:na]
	at com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper.getGraphQLFieldDefinitions(GraphQLObjectMapper.java:673) ~[schemagen-graphql-1.0.1.jar:na]
	at com.bretpatterson.schemagen.graphql.impl.DefaultQueryAndMutationFactory.newMethodQueriesForObject(DefaultQueryAndMutationFactory.java:52) ~[schemagen-graphql-1.0.1.jar:na]
	at com.bretpatterson.schemagen.graphql.GraphQLSchemaBuilder.build(GraphQLSchemaBuilder.java:230) ~[schemagen-graphql-1.0.1.jar:na]
```

**Comment by cliedeman** [comment]
Hi there

I have created PR #11 to fix this issue.
cc @bpatters 

Ciaran

**Comment by bpatters** [comment]
Thanks for the fix @ciara
