### ISSUE TITLE
GraphQLObjectMapper is throwing exception when building Classes Hierarchy

### ISSUE THREAD

**Issue by alissongodoi** [bpatters/schemagen-graphql#15]
GraphQLObjectMapper is throwing exception in the typeArguments stack. It follows attached the log.
```
at java.util.Stack.peek(Unknown Source) ~[na:1.8.0_121]
at com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper.getClassFromType(GraphQLObjectMapper.java:742) ~[schemagen-graphql-1.0.2.jar:na]

```

Basically I have the following classes:

```
public abstract class BaseEntity<ID> implements IdentifiedObject<ID>, VersionedEntity {
   @Id
   private ID id;

   public ID getId() {
       return id;
   }
   public void setId(ID id) {
       this.id=id;
   }	
}
```

```
public class Person extends BaseEntity<Long> implements IdentifiedObject<Long> {
    // Person details
}

```
It fails in the build:

```
KeyValueStoreController key = new KeyValueStoreController();
ObjectMapper objectMapper = new ObjectMapper();
GraphQLSchema schema = GraphQLSchemaBuilder.newBuilder()
    .registerTypeFactory(new JacksonTypeFactory(objectMapper))
    .registerGraphQLControllerObjects(ImmutableList.<Object>of(key))
    .build();
```

typeArguments variable is empty. It is trying to fetch variable type ID.
`getClassFromType(typeArguments.peek().get(((TypeVariable<?>) type).getName()));`

**Comment by cliedeman** [comment]
Hi @alissongodoi 

I have created a fix for this issue in PR #17.

The cause was the library not handling the case Person extends Entity<ID> correctly. 

I have added some code using `getSuperclass()` to cater for this Scenario.

If the meantime you can create a custom type mapper to workaround the problem (not a real solution I know).

Ciaran
